Creating weather dataframe from website

In [1]:
import requests
import json
city = 'Ahmedabad'
api_key = 'c3a3ac8343bad8fc4954066387659183'
req_url = f'http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api_key}'
response = requests.get(req_url)
res = response.json()
res

[{'name': 'Ahmedabad',
  'local_names': {'kn': 'ಅಹ್ಮದಾಬಾದ್',
   'en': 'Ahmedabad',
   'cs': 'Ahmadábád',
   'mr': 'अहमदाबाद',
   'te': 'అహ్మదాబాద్',
   'ml': 'അഹമ്മദാബാദ്',
   'hi': 'अहमदाबाद',
   'uk': 'Ахмедабад',
   'ru': 'Ахмадабад',
   'pa': 'ਅਹਿਮਦਾਬਾਦ',
   'he': 'אחמדאבאד',
   'ascii': 'Ahmedabad',
   'ar': 'أحمد آباد',
   'de': 'Ahmedabad',
   'zh': '艾哈迈达巴德',
   'or': 'ଅହମଦାବାଦ',
   'feature_name': 'Ahmedabad',
   'gu': 'અમદાવાદ',
   'oc': 'Ahmadabad',
   'ta': 'அகமதாபாத்',
   'eo': 'Ahmadabado',
   'pl': 'Ahmadabad',
   'ja': 'アフマダーバード',
   'ur': 'احمد آباد'},
  'lat': 23.0216238,
  'lon': 72.5797068,
  'country': 'IN',
  'state': 'Gujarat'}]

In [2]:
lat = str(res[0]['lat'])
lon = str(res[0]['lon'])
print(lat,lon)

23.0216238 72.5797068

In [3]:
url = f'https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}'
response = requests.get(url)
resu = response.json()
x = (json.dumps(resu,indent=4))
print(x)

{
    "coord": {
        "lon": 72.5797,
        "lat": 23.0216
    },
    "weather": [
        {
            "id": 711,
            "main": "Smoke",
            "description": "smoke",
            "icon": "50d"
        }
    ],
    "base": "stations",
    "main": {
        "temp": 305.19,
        "feels_like": 307.12,
        "temp_min": 305.19,
        "temp_max": 305.19,
        "pressure": 1012,
        "humidity": 48
    },
    "visibility": 5000,
    "wind": {
        "speed": 2.57,
        "deg": 270
    },
    "clouds": {
        "all": 20
    },
    "dt": 1696923334,
    "sys": {
        "type": 1,
        "id": 9049,
        "country": "IN",
        "sunrise": 1696899844,
        "sunset": 1696942159
    },
    "timezone": 19800,
    "id": 1279233,
    "name": "Ahmedabad",
    "cod": 200
}

In [4]:
url1=f'http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid={api_key}'
response = requests.get(url1)
res1 = response.json()
x = (json.dumps(resu,indent=4))
dt = {1:"good",2:'fair',3:'moderate',4:'poor',5:'pathetic'}
y = res1['list'][0]['main']['aqi']
print(y,dt[y])

2 fair

In [5]:
import pandas as pd
url2=f'http://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={api_key}'
response = requests.get(url2)
res2 = response.json()
x = (json.dumps(res2,indent=4))
d_t = []
temp = []
pr = []
hu = []
wd = []
ws = []
for i in range(len(res2['list'])):
    temp.append(res2['list'][i]['main']['temp'])
    d_t.append(res2['list'][i]['dt_txt'])
    pr.append(res2['list'][i]['main']['pressure'])
    hu.append(res2['list'][i]['main']['humidity'])
    wd.append(res2['list'][i]['weather'][0]['description'])
    ws.append(res2['list'][i]['wind']['speed'])
data = pd.DataFrame({'date_time':d_t,'temp':temp,'pressure':pr,'humidity':hu,'weather_description':wd,'wind_speed':ws})

In [6]:
data

,date_time,temp,pressure,humidity,weather_description,wind_speed
0,2023-10-10 09:00:00,305.19,1012,48,few clouds,3.32
1,2023-10-10 12:00:00,305.52,1011,43,few clouds,1.08
2,2023-10-10 15:00:00,303.02,1011,46,clear sky,0.89
3,2023-10-10 18:00:00,300.43,1012,50,clear sky,1.69
4,2023-10-10 21:00:00,299.05,1010,64,few clouds,1.33
5,2023-10-11 00:00:00,298.30,1011,67,broken clouds,1.06
6,2023-10-11 03:00:00,300.42,1014,65,scattered clouds,1.14
7,2023-10-11 06:00:00,305.04,1013,48,few clouds,1.15
8,2023-10-11 09:00:00,307.60,1010,36,clear sky,1.74
9,2023-10-11 12:00:00,306.38,1010,41,clear sky,1.24
10,2023-10-11 15:00:00,303.28,1011,46,clear sky,1.90
11,2023-10-11 18:00:00,302.08,1012,48,clear sky,1.25
12,2023-10-11 21:00:00,300.39,1011,54,clear sky,1.80
13,2023-10-12 00:00:00,299.67,1011,59,clear sky,1.07
14,2023-10-12 03:00:00,301.93,1013,54,clear sky,1.32
15,2023-10-12 06:00:00,306.31,1013,39,clear sky,1.46
16,2023-10-12 09:00:00,308.43,1010,29,clear sky,2.16
17,2023-10-12 12:00:00,306.84,1011,36,clear sky,1.31
18,2023-10-12 15:00:00,303.85,1012,40,clear sky,1.86
19,2023-10-12 18:00:00,302.41,1012,44,clear sky,1.63
20,2023-10-12 21:00:00,300.99,1011,51,clear sky,1.67
21,2023-10-13 00:00:00,300.67,1012,51,clear sky,0.84
22,2023-10-13 03:00:00,302.33,1014,49,clear sky,1.78
23,2023-10-13 06:00:00,306.72,1014,38,clear sky,2.51
24,2023-10-13 09:00:00,308.76,1011,32,clear sky,2.47
25,2023-10-13 12:00:00,307.15,1010,37,clear sky,0.65
26,2023-10-13 15:00:00,304.36,1012,40,clear sky,1.37
27,2023-10-13 18:00:00,303.57,1012,43,scattered clouds,0.52
28,2023-10-13 21:00:00,301.97,1010,48,scattered clouds,0.70
29,2023-10-14 00:00:00,300.80,1011,51,few clouds,1.75
30,2023-10-14 03:00:00,302.48,1014,51,clear sky,0.95
31,2023-10-14 06:00:00,306.71,1014,39,clear sky,0.66
32,2023-10-14 09:00:00,308.61,1010,33,clear sky,1.96
33,2023-10-14 12:00:00,307.48,1010,36,few clouds,0.74
34,2023-10-14 15:00:00,304.47,1012,41,scattered clouds,1.04
35,2023-10-14 18:00:00,304.13,1012,42,scattered clouds,0.14
36,2023-10-14 21:00:00,302.62,1010,45,overcast clouds,3.15
37,2023-10-15 00:00:00,300.70,1010,56,broken clouds,2.79
38,2023-10-15 03:00:00,301.61,1013,59,few clouds,3.85
39,2023-10-15 06:00:00,305.84,1012,41,clear sky,2.31